### ISSUE TITLE
Unable to migrate v1 to v2 - db error

### ISSUE THREAD

**Issue by Dulanic** [theotherp/nzbhydra2#106]
You don't have to follow this template by the letter, just think about what you're trying to achieve ;-) 

## How to do a bug report

* What do you expect to happen? What does happen? 
Expected to migrate from v 1 to v2. Instead it errors out.
* Have you searched for this problem? You don't have to answer, just make sure.
* Can the problem be reproduced? How?
Yes, if I try to migrate again.
* Use a proper title. Describe the problem succinctly, don't just copy and paste the error message.

**Set your log file level to debug, repeat the steps that cause the problem and post the debug info which can be retrieved in the [System / Bugreport section](http://127.0.0.1:5076system/bugreport). If other tools are involved post their logs as well.**
[nzbhydra-debuginfos-2018-02-01-14-22.zip](https://github.com/theotherp/nzbhydra2/files/1687091/nzbhydra-debuginfos-2018-02-01-14-22.zip)
**I will close your issues if I you didn't provide proper information as described as above**

The more information you provide up front the higher the chance that I can help you.

## How to request a new feature
* What do you want to happen? Migrate from v1 to v2
* If not clear, why do you want it?
* Do you think it's something only you need or something that might be popular?
* If need be explain the use case.

I've tried both the URL migration and the db/cfg file migration and both come back with the same issues. Both containers are the LS.io hydra containers.

**Comment by theotherp** [comment]
On Discord you wrote "i copied the files into a subdir called hydra1". 

The log shows multiple tries:

1. you entered your v1 IP which doesn't work because you're running containers
2. you entered the file paths `/docker/containers/hydra/config/hydra` and `/docker/containers/hydra/config/hydra` in the migration dialog. That doesn't work because you're running containers and the absolute paths on your host machine don't work inside the container
3. you entered the file paths `/config/hydra1/settings.cfg` and `/config/hydra1`. The latter one can't be correct because it's apparently a folder
4. some other wrong stuff
5. some different stuff that's wrong
6. you entered the file paths  `/config/hyrdra1/settings.cfg` and database file `/config/hyrdra1/nzbhydra.db.*`

It looks like you tried about every possible combination...  I think you mean `/config/hydra1/settings.cfg` and `/config/hydra1/nzbhydra.db`

**Comment by Dulanic** [comment]
Wow I tried everything but the one thing I should have. Thanks for the assistance, all clear now. I think the comment above the field showing /config/hyrdra1/nzbhydra.db.* threw me off.
