### ISSUE TITLE
Nzbgeek

### ISSUE THREAD

**Issue by danjames92** [theotherp/nzbhydra2#119]
Seeing this

Not using NZBGeek because it's disabled until re-enabled by user

It's enabled... :) v.1.3.3

**Comment by fryfrog** [comment]
Try renaming it and saving it, then renaming it back and saving it. Are you seeing this when you do a search or in the indexer status page? The status page will show the last error, no matter what. Even if it is enabled and hasn't been disabled.

**Comment by danjames92** [comment]
Yep that fixed it!

Weird.

**Comment by theotherp** [comment]
Well, it was disabled for a good reason, usually because the API key was not correct or something like that. The indexer status page shows the reason.

I'll move the indexer status display for disabled indexers to the indexer config in future version.

**Comment by danjames92** [comment]
It wasn't a wrong api key that's for sure...

the renaming fixed it. @theotherp

**Comment by fryfrog** [comment]
https://www.reddit.com/r/nzbhydra/comments/7rhjus/not_using_nzbgeek_because_its_disabled_until/

^ I think this is like the above issue. Despite all my indexers being *not* disabled, a few of them say they're not being used during a search because they're disabled by the user, but they're not disabled.

**Comment by theotherp** [comment]
@danjames92 Aaargh why do you all insist on completely ignoring the issue template. Just post the debug infos as requested.

**Comment by danjames92** [comment]
@theotherp you're missing the point but ok point taken.

I never had Geek disabled in the first place! It was always enabled but Hydra wasn't using it!

**Comment by theotherp** [comment]
No I'm not missing the point. My point is that 

a) the issue template CLEARLY says to post the debug infos and how to do a bug report but you just fucking ignored it

b) the indexer was disabled because an error occurred, not because you disabled it. That's not the same.

Jesus fucking christ, you people sometimes really make it hard to help you.

**Comment by fryfrog** [comment]
The hard part about noticing that is the in progress search box is only up for a few seconds, it isn't surprising that reading one line out of a bunch while the pop up is only visible for a handful of seconds results in poor comprehension of it. :(

**Comment by theotherp** [comment]
That's why I at least try to make the log output useful. But if nobody reads it or even posts it why do I care.

I'll try to think of a better wording and make the different types of "disabledness" better recognizable.

**Comment by jalmansor** [comment]
@theotherp I care, and I highly appreciate the effort.
