### ISSUE TITLE
403 Forbidden Consistently (Synology Docker Container)

### ISSUE THREAD

**Issue by Elfman72** [theotherp/nzbhydra2#122]
Similar to bug #89 and #101, I am experiencing this error which is preventing me from seeing the latest updates for Hydra.

Seemed to start happening around version 1.3.0.  I have restarted my container several times as well as re-built my container several times with very little success.  After rebuilding the last go around, I did get the expexcted notificaion that I needed to upgrade to 1.4.0 (and that I was running in Docker).  However, once I enabled Authentication and restarted the container, my upgrade message disappeared and now has nothing in either the 'Current Version' or 'Latest Version' fields.

![hyd](https://user-images.githubusercontent.com/3315407/36159869-ad301aec-1094-11e8-97a9-eef1358de26c.PNG)

The exact error messages are as follows:
* An error occurred while updating or getting update infos: Error while getting latest version: URL call to https://api.github.com/repos/theotherp/nzbhydra2/releases/latest returned 403: Forbidden

* URL call to https://api.github.com/repos/theotherp/nzbhydra2/releases/latest returned 403: Forbidden

![hyd2](https://user-images.githubusercontent.com/3315407/36159932-cfb96488-1094-11e8-9ad9-c4d979e0e95d.PNG)

I have attempted this with both[ your Docker image](https://hub.docker.com/r/theotherp/nzbhydra2) and [LinuxServer's docker image](https://hub.docker.com/r/linuxserver/hydra2/) with the same result.  I am running this container behind a reverse proxy with a Let's Encrypt cert.  

I did read something on Stack Overflow about prefacing the link used to make the call with a unique identifier.  I didn't read all of it and not sure if it applies or not
https://stackoverflow.com/questions/7438313/pushing-to-git-returning-error-code-403-fatal-http-request-failed

So currently, the only way for me to get the latest builds is to re-build my Hydra 2 container each time which means having to re-add my downloader info as well as my many indexer APIs.  A very manual process.

Let me know how I can help.  

Additionally, it does seem to be IP address related.  Meaning, I can click on [this link](https://api.github.com/repos/theotherp/nzbhydra2/releases/latest) at home and am given the follwoing message.  
![hyd4](https://user-images.githubusercontent.com/3315407/36162529-96bb6738-109b-11e8-81f4-300d2a0f21ba.PNG)

If I fire up a VPN, I can see the page perfectly fine.
![hyd3](https://user-images.githubusercontent.com/3315407/36162292-e10cb540-109a-11e8-9a8b-802b56c9a384.PNG)

**Comment by theotherp** [comment]
I was told by multiple docker container maintainers that updating the
container instead of the content is the way to go. But I'm not gonna
require you to do that, it should obviously still work.

Anyway, thanks for doing some research before posting. I still haven't
found out why this happens. Neither have I found a way to reproduce it
which makes it impossible for me to test any potential fix. Short of
proxying the update Infos via some other server I can't think of a
solution.

Please enable debug log level for the log file and in the logging markers
setting select "HTTP" (or something like that). Reproduce the problem and
then post the debug infos zip.


Am 13.02.2018 17:12 schrieb "Elfman72" <notifications@github.com>:

Similar to bug #89 <https://github.com/theotherp/nzbhydra2/issues/89> and
#101 <https://github.com/theotherp/nzbhydra2/issues/101>, I am experiencing
this error which is preventing me from seeing the latest updates for Hydra.

Seemed to start happening around version 1.3.0. I have restarted my
container several times as well as re-built my container several times with
very little success. After rebuilding the last go around, I did get the
expexcted notificaion that I needed to upgrade to 1.4.0 (and that I was
running in Docker). However, once I enabled Authentication and restarted
the container, my upgrade message disappeared and now has nothing in either
the 'Current Version' or 'Latest Version' fields.

[image: hyd]
<https://user-images.githubusercontent.com/3315407/36159869-ad301aec-1094-11e8-97a9-eef1358de26c.PNG>

The exact error messages are as follows:

   -

   An error occurred while updating or getting update infos: Error while
   getting latest version: URL call to https://api.github.com/repos/t
   heotherp/nzbhydra2/releases/latest
   <https://api.github.com/repos/theotherp/nzbhydra2/releases/latest>
   returned 403: Forbidden
   -

   URL call to https://api.github.com/repos/theotherp/nzbhydra2/releases/la
   test returned 403: Forbidden

[image: hyd2]
<https://user-images.githubusercontent.com/3315407/36159932-cfb96488-1094-11e8-9ad9-c4d979e0e95d.PNG>

I have attempted this with both your Docker image
<https://hub.docker.com/r/theotherp/nzbhydra2> and LinuxServer's docker
image <https://hub.docker.com/r/linuxserver/hydra2/> with the same result.
I am running this container behind a reverse proxy with a Let's Encrypt
cert.

I did read something on Stack Overflow about prefacing the link used to
make the call with a unique identifier. I didn't read all of it and not
sure if it applies or not
https://stackoverflow.com/questions/7438313/pushing-to-git-
returning-error-code-403-fatal-http-request-failed

So currently, the only way for me to get the latest builds is to re-build
my Hydra 2 container each time which means having to re-add my downloader
info as well as my many indexer APIs. A very manual process.

Let me know how I can help.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/theotherp/nzbhydra2/issues/122>, or mute the thread

**Comment by Elfman72** [comment]
Here is the debug with just HTTP results pulled out.
[HydraDebug.txt](https://github.com/theotherp/nzbhydra2/files/1720975/HydraDebug.txt)

Here is the entire debug zip
[nzbhydra-debuginfos-2018-02-13-09-42.zip](https://github.com/theotherp/nzbhydra2/files/1720979/nzbhydra-debuginfos-2018-02-13-09-42.zip)

This is from a brand new container I built just this morning using the linuxserver image so the log file is only for this morning and isn't deep.  

I have other git hosted Docker containers on my Synology.  Could it be that all of these apps are version checking and hitting the daily anonymous limit not directly tied to Hydra?  Just Git hosted solutions?  Just a thought.

Again, hope this helps.

**Comment by theotherp** [comment]
The log file log level is still INFO and the logging markers selection empty. It should look like this: https://i.imgur.com/hWgudjR.png

**Comment by Elfman72** [comment]
Apologies for that.  Now I see it.  Thanks for that.

Here is the updated Debug file.  It hasn't been running under degug for long but I did click ont he Updates tab a few times. to ensure it was logging.
[nzbhydra-debuginfos-2018-02-13-10-30.zip](https://github.com/theotherp/nzbhydra2/files/1721131/nzbhydra-debuginfos-2018-02-13-10-30.zip)

**Comment by theotherp** [comment]
Ah shit, I read your initial post while sitting on the loo and skipped the most important parts... You basically did the debugging for me and I didn't see it, sorry :-)

I can't really say why you (and some other users) are exceeding the hit limit while others don't. But considering that authenticated users get higher limits I might add settings for github credentials to the config that will be used. It's not ideal but should do the trick. I'll also adapt the caching so that GitHub requests are not made as often.

I'm hoping to have some time for this on the weekend. Cheers.

**Comment by theotherp** [comment]
By the way, rebuilding or updating the container should not remove any of the saved data. The config and database are saved in a volume of which the content is stored outside the container. I don't really use docker but I'm certain of that. I don't understand why you would need to re-add your downloaders and indexers.

**Comment by Elfman72** [comment]
That is strange for sure.  It isn't like I have a ton of containers running.  Some of them are old (like Headphones) which may be polling every few minutes but I have never come across this until recenlty which is odd.

> By the way, rebuilding or updating the container should not remove any of the saved data. The config and database are saved in a volume of which the content is stored outside the container. I don't really use docker but I'm certain of that. I don't understand why you would need to re-add your downloaders and indexers.

That is what I thought too.  I do have a folder outside the container mapped to the /config variable.  It does populate that folder with the following folders

- backup
- database
- logs
- update

Then these files
- nzbhydra.yml
- nzbhydra.yml.backup
- cacerts (the Linux IO image added this one)

However, when I rebuild the cointainer (In synology, you stop the container, then clear out the contents of the container only, redownload the image, then start the container again.  All variables remain intact and identical as before and the files stay in the folder outside the container), I am always given a prompt stating "This appears to be your first time..." message and have to re-add my DLer, Indexers and change the API key to one all my other tools are using.

Thanks again!

**Comment by pawi** [comment]
I use Watchtower for automatic updates and after an update everything works without initial setup or configuration. Further i don't experience any rate limit issues with GitHub and i run the usual suspects for nzbhydra and even more images. Only issue i have is that there are no more updates since 13 days to theotherp/nzbhydra2 docker image. Any reason for this?

**Comment by theotherp** [comment]
> Only issue i have is that there are no more updates since 13 days to theotherp/nzbhydra2 docker image. Any reason for this?

My linux VM is unable to boot and I haven't had time to fix it. I need it to build and release the docker image.

**Comment by pawi** [comment]
Got a new update through docker, worked without any problem! Again no rate limit issues with Github visible.

**Comment by theotherp** [comment]
I'll consider this fixed.

**Comment by Elfman72** [comment]
Ineed.  So strange. Haven't had any issues since about 2 weeks ago.  Just updated to 1.4.7 without issues.

**Comment by Elfman72** [comment]
Hmm.  As of today, I am seeting this again, with the exact same symptoms (403: Forbidden).

Running version 1.5.1

I still see this error when clicking [this ](https://api.github.com/repos/theotherp/nzbhydra2/releases/latest)link

```
{
  "message": "API rate limit exceeded for 73.53.106.96. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```

I'll try rebuilding my Docker image to see if that helps, but it didn't seem to last time and eventually "fixed itself" last time.

Debug info attached.


[nzbhydra-debuginfos-2018-07-17-20-37.zip](https://github.com/theotherp/nzbhydra2/files/2204305/nzbhydra-debuginfos-2018-07-17-20-37.zip)
