### ISSUE TITLE
Incorrect Capabilities for NZBFinder

### ISSUE THREAD

**Issue by whispy** [theotherp/nzbhydra2#133]
**Expectation:**
- Hydra would find all of the capabilities for NZB Finder, as listed here: https://nzbfinder.ws/api?t=caps

**Result:**
- Hydra only finds `IMDBID` as a capability

**Steps to Reproduce:**
1. Navigate to `Config` > `Indexers` and select `Add new indexer` > `NZB Finder`.
2. Add API key.
3. Run capabilities check on indexer.
4. Hydra only finds `IMDBID` as a supported capability.

- I've tried completely deleting Finder as an indexer, restarting Hydra, then adding Finder in again (both via the preset indexer and from scratch). Neither solved the issue.
- Capability checks for all other indexers appear to find all capabilities.

**System:**
Hydra v1.4.3 (occurred in previous versions too), run in Linuxserver Docker container.

**Debuginfos: (NOTE: In this debuginfos, I ran the capabilities check once _without_ an API key [which resulted in a 403 forbidden error], and then again _with_ an API key [which only found IMDBID as supported])**
https://dl.dropboxusercontent.com/s/vet2jkw0y389o06/nzbhydra-debuginfos-2018-03-04-15-36.zip

**Comment by theotherp** [comment]
This happens because Hydra queries the indexer using certain keys and expects the returned results to contain certain words in the title. For TV I chose a very popular show which I though every indexer would have in the database. This always worked well but now some releases popped up that used the shows' initialism and were therefore not seen as matching results.

**Comment by DariusIII** [comment]
There is a reason for ?t=caps on indexers, you know.

**Comment by theotherp** [comment]
Well, at least half of the indexers lie and either say they support something and don't or vice versa. That's why I stopped believing and implemented this check.

**Comment by DariusIII** [comment]
Maybe you could do both? Check caps and try your current implementation, and if 2 types match use whatever is set in caps?

**Comment by theotherp** [comment]
This has a long history. Before I made these changes in v1 i used to trust the indexers's caps response, then it turned out they were often wrong. In my experience it's usually best to get it straight from a source. If an ID is supported it should return proper results. This approach but has provided very reliable results in the last 18 months with only having two tweak it twice.

Ideally indexers would keep their caps response updated to the rest of their code base but, alas, they do not. Then users come and complain that they think that some IDs are not supported and I can either redirect them to the indexer's staff or find a workaround. I usually do the latter because it's faster and easier.

Currently I don't see any need to change the algorithm but I may at some point.

**Comment by Fossil01** [comment]
Well fuck indexers who lie about their capabilities :D
