### ISSUE TITLE
Feature request: Block fill nzb indexer option to only use indexer in event of 0 results or outage of primary

### ISSUE THREAD

**Issue by tastyratz** [theotherp/nzbhydra2#179]
There are a few indexers out there which offer free accounts with very limited api calls or inexpensive ones that are very limited.
Ideally, I'd like to search something like 6box FIRST and only then if I find 0 results or it's something not normally indexed by 6box (such as books) does it query my "block fill" indexers. Load balancing and api limits aren't really leveraging them ideally.

**Comment by fryfrog** [comment]
There are two settings that you can use to mitigate this a little, but not exactly what you want. You can set api and download limits for indexers and you can round robin them. So if you have 5 free ones with limits, you could set the round robin such that each is used in every 5th query.

It doesn't *really* do what you want, but you can get decent results w/ a bunch of free indexers providing limited queries and downloads.

I don't think I'd vote for this feature due to the complexity it would add for most users. If you're using nzbhydra2 w/ only one or two indexers, you're kind of missing the point. Once you get up to a handful of them, you're just not going to run into a 0 results situation which would negate this feature entirely.

**Comment by theotherp** [comment]
I agree with @fryfrog. I kinda like the idea but this would make Hydra even more complicated than it already is.
