### ISSUE TITLE
API Categories Query

### ISSUE THREAD

**Issue by Adam1986** [theotherp/nzbhydra2#280]
First of all a big thanks for sorting out the blank covers on API :-)

Can I just ask for some clarification, when using NZB 360 on my phone and looking through Movies -> UHD, I only appear to get results from DS which uses category 2045 for Movies UHD.  NZBPlanet uses category 2070 for Movies UHD.

Within Hydra2, if i create a new category, say UHD Test, and add both Newznab categories in, then I can search through the web interface and see results from both indexers as you'd expect.  But this category doesn't pull through into the API.

Is this expected? and is there a way around it to get API to search both 2045/2070 as I am guessing the API search is only querying category 2045?

Cheers
Adam

**Comment by theotherp** [comment]
This is due to the fact that, as you say, indexers use different numbers for special categories (such as UHD which isn't defined in the standard).

There's no (ridiculously complicated) way of fixing this.  When an API search comes in for a certain category number (say 2045) how do I know what category is "really" meant? Is this UHD (interpreting using DS's mapping) or is this something unknown (using NZBPlanet's mapping)? Same problem the other way around.

When you search using the GUI I know exactly which category you mean and can use it to search the indexers. There will be some wrong results (because I search both indexers using categories 2045 and 2070) but that's a different matter.

I experimented creating the caps page (which lists the categories for NZB360) using the internal config. It would look like this (for the default category config):
```
<categories>
    <category id="1000" name="Console"/>
    <category id="2000" name="Movies">
        <subcat id="2040" name="Movies HD"/>
        <subcat id="2050" name="Movies HD"/>
        <subcat id="2060" name="Movies HD"/>
        <subcat id="2070" name="Movies HD"/>
        <subcat id="2030" name="Movies SD"/>
    </category>
    <category id="3000" name="Audio">
        <subcat id="3030" name="Audiobook"/>
        <subcat id="3040" name="FLAC"/>
        <subcat id="3010" name="MP3"/>
    </category>
    <category id="4000" name="PC"/>
    <category id="5000" name="TV">
        <subcat id="5070" name="Anime"/>
        <subcat id="5040" name="TV HD"/>
        <subcat id="5030" name="TV SD"/>
    </category>
    <category id="6000" name="XXX"/>
</categories>
```

Doesn't really help, does it?

To work around this matter when an API search provides categories only those are used, without transforming them.

I guess one possible approach would be to extend the search with all the newznab categories found in a category if one of those is provided. So a search using "cat=2050" would be transformed to "cat=2040,2050,2060,2070". 

If I did that then I could only provide the first newznab number for a category:
```
<categories>
    <category id="1000" name="Console"/>
    <category id="2000" name="Movies">
        <subcat id="2040" name="Movies HD"/>
        <subcat id="2030" name="Movies SD"/>
    </category>
    <category id="3000" name="Audio">
        <subcat id="3030" name="Audiobook"/>
        <subcat id="3040" name="FLAC"/>
        <subcat id="3010" name="MP3"/>
    </category>
    <category id="4000" name="PC"/>
    <category id="5000" name="TV">
        <subcat id="5070" name="Anime"/>
        <subcat id="5040" name="TV HD"/>
        <subcat id="5030" name="TV SD"/>
    </category>
    <category id="6000" name="XXX"/>
</categories>
```

Sounds plausible, but I'm not sure what side effects this might have...

**Comment by theotherp** [comment]
Hm, seems to work. I might just push it and see who complains -.-
