### ISSUE TITLE
Server returned: java.net.ConnectException

### ISSUE THREAD

**Issue by stefanschramek** [theotherp/nzbhydra2#316]
Hi!
Everything worked until yesterday when I updated to the latest version - I already installed the latest version manually today.
The indexer "newz-complex" is not working anymore, and I face the following error:

> Error while accessing indexer: Error while communicating with indexer NewzComplex. Server returned: java.net.ConnectException: Failed to connect to newz-complex.org/2606:4700:30:0:0:0:681b:b782:443

The URL is a little strange, as I added to indexer with the following settings

![image](https://user-images.githubusercontent.com/921342/52549069-93a52800-2dd1-11e9-9136-4cf9105e5a4f.png)

[nzbhydra-debuginfos-2019-02-11-07-45.zip](https://github.com/theotherp/nzbhydra2/files/2850054/nzbhydra-debuginfos-2019-02-11-07-45.zip)

Thanks
Stefan

**Comment by theotherp** [comment]
Yeah, that's weird. I added the indexer to my hydra instance and I was able to connect to it just fine. I don't have an account there so no API key and I can't completely test it, but at least I can connect to it.

I think there's something really wacky going on with DNS resolution or network pathing or whatever you call it (not my specialty). `2606:4700:30::681b:b782` is the ipv6 address of the domain `newz-complex.org`. Why would that be used instead of the "www" in the URL?

Can you temporarily disable ipv6 on your system and try again?

**Comment by stefanschramek** [comment]
> Yeah, that's weird. I added the indexer to my hydra instance and I was able to connect to it just fine. I don't have an account there so no API key and I can't completely test it, but at least I can connect to it.
> I think there's something really wacky going on with DNS resolution or network pathing or whatever you call it (not my specialty). 2606:4700:30::681b:b782 is the ipv6 address of the domain newz-complex.org. Why would that be used instead of the "www" in the URL?
> Can you temporarily disable ipv6 on your system and try again?

I disabled it - but no success.
Actually I think that the app is somehow connected to this behavior, as It worked before the update.
Even a ping resolved to the correct IPv4 and not v6?
Are you sure it's about the path?
I thought maybe your app creates the entry in the log file "host/IP" - so its a little bit confusing?

**Comment by theotherp** [comment]
The log entry just looks like that because it tries to anonymize sensitive data. In `newz-complex.org/<IP>:443` the `<IP>` is just the ipv6 address that matches a certain regular expression. Your screenshot shows the original value.

Please go to the main settings and set the file log level to debug and enable the logging marker HTTP. Retry adding the indexer and post the new debug infos.

**Comment by stefanschramek** [comment]
Here you go!
Thanks!
[nzbhydra-debuginfos-2019-02-11-16-56.zip](https://github.com/theotherp/nzbhydra2/files/2851855/nzbhydra-debuginfos-2019-02-11-16-56.zip)

**Comment by theotherp** [comment]
I have no idea what is happening, sorry...

**Comment by theotherp** [comment]
I'm pretty sure it has something to do with your computer and its network because a) I cannot reproduce it and b) why else and how would the hosts ipv6 address appear there?

I was mislead by the error message but `newz-complex.org/2606:4700:30:0:0:0:681b:b782:443` is just a special way of describing the host and its port.

**Comment by stefanschramek** [comment]
Don't get me wrong - I really appreciate your work here and I cannot expect anything because it's free software.
But NZBHydra2 was working for months without any issue in a jail on FreeNAS. After the latest updates it stopped working. I can successfully add the indexer to Radarr directly without any issues.
I cannot believe it is connected to network issues - because all Jails have the same network config (except the IP address).
DNS resolutions shows me on both IPv4 and IPv6, ping uses IPv4.
For my understanding the software chooses IPv6 now - and maybe my network is not ready for this. But if there were some changes if would be nice to have the option to let me choose IPv4 or IPv6.
Thanks for you work!
Stefan

**Comment by theotherp** [comment]
Have you updated to 2.3.13?

**Comment by h45rd** [comment]
NewzComplex is working fine for me with the latest version of hydra. But I am using a docker container without IPv6 connectivity.
Not sure when they added the AAAA record to their DNS, but maybe it coincides with the start of your problems?

It's not hydra that "chooses" to prefer IPv6 over IPv4 (which would be desirable in most cases on true dual stack connections), it is your OS.
How did you disable IPv6 during your tests? Using iocage only on the specific jail or system-wide?

I see no reason hydra would not work with IPv6, though. As long as your network provides connectivity and the remote server is configured to actually serve via IPv6.

**Comment by stefanschramek** [comment]
Yes - already updated the binaries to latest version today.
I disabled it just for this single jail.
I added now "-Djava.net.preferIPv4Stack=true" to the wrapper - found this during research.
But now I get "javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure" errors.
So don't know if I am on the right way or making it worse...

**Comment by theotherp** [comment]
I've gone over all changes between 2.3.6 and 2.3.13. All changes to HTTP access or SSL were reverted. I understand this may be frustrating but I can't explain why your problem occurs now. I can't reproduce it so there's really nothing I can think of to help you.

**Comment by h45rd** [comment]
Hmm.. since it does not concern me, I did not follow this topic closely.
But you could be facing one of the SSL issues @theotherp has been battling since the framework update for Java 11 in 2.3.0.

Does temporarily switching off SSL verification for this specific indexer alleviate the issue?
Alternatively: does accessing the indexer without SSL work?
Strangely enough NC works for me with SSL and without any workarounds. But my docker container is on OpenJDK 10.0.2. I guess you are using Java 11?

You can try debugging it further by using `openssl s_client -connect` (see `man openssl s_client` for more verbosity options) within the jail.
A quick check seems to suggest a server-side issue, since it indeed yields:

> SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:../ssl/record/rec_layer_s3.c:1399:SSL alert number 40

But when explicitly [setting the TLS SNI extension](https://www.openssl.org/docs/man1.0.2/man1/s_client.html) via the -servername parameter, the handshake goes through without a hitch.
Need to further research in order to determine if this is a server- or client-side issue.

**Comment by theotherp** [comment]
Please try with 2.3.13. Who knows, might've helped.

@h45rd Thanks for chiming in. In this particular case it looks like Hydra can't connect to the host at all, before it can do any SSL handshake.

**Comment by stefanschramek** [comment]
I gave it another try today and reinstalled it from scratch with the latest version - and it's working again!
I don't know if there were some changes in the code that fixed it, or if the indexer guys changed something...
Thanks for your help!
