### ISSUE TITLE
Browser window / tab with NZBHydra crashes after some time

### ISSUE THREAD

**Issue by theotherp** [theotherp/nzbhydra2#379]
The browser tab crashes after some hours with NZBHydra open. Might be related to the downloader status bar. Have been unable to debug this. Performance / memory snapshots don't show anything unusual for a long time and then at some point the tab crashes.

**Comment by soupy14** [comment]
Not too sure how to word this correctly but for the past two days I have left hydra as the main tab showing/open and it doesn't seem to crash. When I select over and say have Sabnzb or another tab showing hydra seems to crash after a period of time.  I will keep testing to see how I can duplicate this. I have cleared the cache no difference I have a lot of memory already assigned to hydra so I know that isn't the cause.

**Comment by samkatakouzinos** [comment]
[nzbhydra-debuginfos-2019-06-26-12-19.zip](https://github.com/theotherp/nzbhydra2/files/3327918/nzbhydra-debuginfos-2019-06-26-12-19.zip)
Same issue, crashed page.

**Comment by BzowK** [comment]
Hey Guys - 

+1 - I have the same issue and found this post when searching for a similar one prior to posting about it as it's frustrating to say the least.  Below are notes about my encounters followed by environment details:

**Notes**
- If tab is inactive for some time _(haven't measured)_, switching back to it shows "something went wrong" Chrome message in otherwise blank webpage
- Reloading the tab works, but causes the search to be performed again so as mentioned by another, faster to launch new tab
- Reviewed log files, but nothing abnormal appears during time window
- To show how it's launched, below are last two lines from wrapper.log:

> INFO - Determined java version as '8' from version string 'java version "1.8.0_231"'
> INFO - Starting NZBHydra main process with command line: java -Xmx256M -DfromWrapper -XX:TieredStopAtLevel=1 -noverify -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=C:\NZBHydra2\data\logs -Xloggc:data\logs\gclog-2019-11-03_19-28-18.log -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintTenuringDistribution -XX:+PrintGCCause -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=5M -jar C:\NZBHydra2\lib\core-2.7.5-exec.jar --datafolder C:\NZBHydra2\data in folder C:\NZBHydra2

**Environment**
- Chrome _(Enterprise)_ x64 on Windows 10 x64
- NZBHydra2 2.7.5 installed on separate Windows 10 system on LAN than one I'm testing from
- System its installed on uses Java 8 Update 231 _(Build 1.8.0_231-b11)_
- Use a URL Base _(/search)_
- Accessing via nginx reverse proxy which also applies an SSL layer
- Testing accessing using IP:port _(bypassing nginx/RP/SSL)_ and will soon post results
- 

Happy to submit additional detail if needed - Thanks

**Comment by theotherp** [comment]
Should be fixed with next release.
