### ISSUE TITLE
10th indexer doesn't search

### ISSUE THREAD

**Issue by Wdavery** [theotherp/nzbhydra2#399]
I have 10 indexers in Hydra right now, and from the search page only 9 are visible on the screen to select. Even if I click select all, the 10th indexer does not enable, as I can see from the search results "Indexer Statuses". It shows "Not selected by the user" for that entry

**Comment by theotherp** [comment]
Wat

**Comment by Wdavery** [comment]
Would screenshots help?

**Comment by theotherp** [comment]
I'm sorry, the notification mail for this issue was completely empty and the title was cut off, so I only got "10th indexer doesn"...

Please do the following:

1. Enable debug log file level in the main config
2. Enable the logging marker for indexer selection
3. Recreate the problem
4. Create the debug infos ZIP (see system section -> bugreport)
5. Post the ZIP and tell me which indexer isn't selected

**Comment by Wdavery** [comment]
Can't reproduce since updating.
