### ISSUE TITLE
Error while communicating with indexer: org.nzbhydra.indexers.exceptions.IndexerUnreachableException: Error while communicating with indexer oznzb. Server returned: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure

### ISSUE THREAD

**Issue by paulkoorn** [theotherp/nzbhydra2#427]
hey i keep getting ssl handshake error i updated everything to latset java and all.
bin happening for the last few months.
[nzbhydra-debuginfos-2019-08-11-18-58.zip](https://github.com/theotherp/nzbhydra2/files/3490213/nzbhydra-debuginfos-2019-08-11-18-58.zip)

**Comment by DrakeJones** [comment]
And then....?

**Comment by theotherp** [comment]
I've just released a version with better debugging of SSL issues.

Please do the following:
1. Update to 2.11.1
2. In the main config enable the logging marker "HTTPS"
3. Restart Hydra
4. Execute the caps check for nzbgeek
5. Create the debug infos zip and post them here again
6. Disable the logging marker again and restart Hydra (otherwise it will write a huuuge file in the logs folder).

Thank you.

**Comment by Routhinator** [comment]
TLS 1.0 and 1.1 have been disabled and there is a post on NZBGeek that all connections need to use 1.2 to work now. This required mono updates for sonarr radar, but I've validated my mono is at the correct version. I need to check the debugging but I believe NZBHyrda2 is not using TLS 1.2
