### ISSUE TITLE
- Manual search returns limited results

### ISSUE THREAD

**Issue by bluelavalamp** [theotherp/nzbhydra2#471]
[nzbhydra-debuginfos-2019-12-11-06-45.zip](https://github.com/theotherp/nzbhydra2/files/3950148/nzbhydra-debuginfos-2019-12-11-06-45.zip)

Hi,
I'm running version v2.10.2 (2019-12-04) (not in docker or anything like that, just running it straight on Linux) and I noticed I think it was after I updated to version 2.10 that when I manually search I get very limited results.  I'm using a decent number of indexers:

Binsearch, Drunken Slug, FastNZB, NZB Finder, NZBGeek, NZBIndex, NzbNdx, Tabula-Rasa, nzbplanet

But I get super limited number of results at the bottom.  For example, if I search for Ghost Adventures, I used to get a couple pages worth of results, now I get 4.  But the floating window that opens up and tells me how many results each provides while checking the indexers, it lists in the hundreds.  

If you need any more info let me know.

Thanks

**Comment by theotherp** [comment]
I guess Ghost Adventures is a TV show and the option to group episodes together is enabled. Check the results and see if there's a plus symbol to the left. Click it to expand the results. To disable that click the display options button.

**Comment by bluelavalamp** [comment]
Ok, that showed some more but not all.  I now found the "Load More" button on the right hand side, when I pick "Load All" then I get all the results.

What's odd is that in my Config->Searching under the Result Processing section, I have "Load all results" turned to On.

**Comment by theotherp** [comment]
That's a bug, then. I redid the implementation a couple of weeks ago.

**Comment by rrd911** [comment]
Having the same issue. Using the docker image. Only get the first 100 and if I sort by size it only sorts the 100

**Comment by albino1** [comment]
I'm having this issue as well I believe.  I have `Load all results` enabled in Config -> Searching, but when I do an internal search I only get 100 results, and there's only 1 page.  Sorting or Filtering only works with the results on that page, so you can't access any of the other results without using the Load More button.

I think it's always said only 100 results were being displayed, but I'm pretty sure that if you sorted or filtered it would work with all the results, and you would be able to access more by going to Page 2, 3, etc.

I'm using 2.10.8 and here's some screenshots showing my settings, the result limit, and how there's no second page:

![al-nzbh4](https://user-images.githubusercontent.com/12164957/72129776-540df580-332c-11ea-8658-3c38678f0103.jpg)

![al-nzbh2](https://user-images.githubusercontent.com/12164957/72129778-54a68c00-332c-11ea-90da-c60134c899bb.jpg)

![al-nzbh1](https://user-images.githubusercontent.com/12164957/72129779-54a68c00-332c-11ea-916e-cd955e9816a3.jpg)

![al-nzbh3](https://user-images.githubusercontent.com/12164957/72129777-54a68c00-332c-11ea-9091-59a83c7af317.jpg)

**Comment by theotherp** [comment]
Yes, I know...

**Comment by albino1** [comment]
Apologies, I thought you had closed this, but I now see that you re-opened it.

**Comment by theotherp** [comment]
See my edit above.

**Comment by albino1** [comment]
That explains a lot, thank you for the update and thorough explanation.

If you're getting more than 100 results from an individual indexer then your search probably isn't specific enough, but if you're getting more than 100 results from all of your indexers combined, then I think that's very common, especially if you have a lot of indexers enabled.  Even searching for a single episode of a popular TV show is going to return potentially hundreds of results between all of them, even if individually they're only returning 10-50 each.

I don't know what the preferred method of dealing with that is either, but defaulting it to no additional API searches and putting in a setting to allow them seems reasonable.

In the meantime, would it not be possible to go back to how it was before, where all results that didn't require additional API queries were cached?  That way we could at least search within the available results and filter.  I now understand that the previous method couldn't correctly be called "all" of the results, but I think it would be an improvement on the current situation.

**Comment by theotherp** [comment]
As I said, the new mechanism is overall better for API searches, but not for GUI searches. I might revert to the old way just for GUI searches, but I'm not sure that I really want that. I'm still considering how to fix this so that we get the best behavior in all cass.

When I updated the new implementation to actually read all I had complaints from users who waited minutes for their results because Hydra would pull up to 10 pages from an indexer which took 20 seconds to response. That's extreme, but in that case the GUI would not return for more than three minutes. Even if that's "the user's fault" because he configured Hydra that way I know that some users will report it as a problem, so I want to prevent that.

I may have some time on the weekend to ponder over this.

**Comment by albino1** [comment]
Completely understandable, I totally see where you're coming from.

I'm not sure requesting additional pages from a single indexer by default is the right behavior as I think very few people would benefit from that, and if they needed it in some specific instance they could use the Load More button.  If you added it as an option like you mentioned before that could work.  Maybe when they tried to enable it if you put a big disclaimer warning that searches may take significantly longer that would avoid some of the complaints and support headaches.  Certainly people that use the GUI instead of only the API could at least see a warning or a message on the indexer status page, or above the loaded results, and then choose to disable it.  Just thinking out loud.

**Comment by theotherp** [comment]
I've just released a beta with hopefully the old behavior. If you'd like you can test it.

**Comment by albino1** [comment]
Much better now, thanks for the fix!  I appreciate it.
