### ISSUE TITLE
 Several issues I'm experiencing with nzbhydra2 on Windows 10 Pro 1903

### ISSUE THREAD

**Issue by AtariBaby** [theotherp/nzbhydra2#497]
Let me know if you'd prefer to have these broken into seveeral issues. They are not really repeatable so I'm attaching logs but not repeating steps in DEBUG mode. I hope that's okay.

Server stats are incorrect. Especially with Dognzb and one other. As a result, they are frequently temporarily disabled when they don't need to be, and dog always seems to be disabled. But also, I an check the indexer sites and hyrdra's stats, and they are way off usually. 
[nzbhydra-debuginfos-2020-02-01-13-55.zip](https://github.com/theotherp/nzbhydra2/files/4143299/nzbhydra-debuginfos-2020-02-01-13-55.zip)
I suspect other stats are incorrect as well.

Recently, I've had trouble with updates. The install message eventually says "taking longer than expected, you may want to check the log". I often have to quit more than once to get it to restart finally. Any idea why?

In task manager, I see two instances of nzbhydra2 console.exe, at all times. Is that normal?

I always found it slow, as others have mentioned, to access nzbhydra from the internet. I have proper portforwarding set up. All my other web services work fine this way: sonarr, radarr, etc. But in the last week or two, I've been unable to access it at all. The browser wheel spins for a minute and then it says "the server stopped responding". Any idea why?

thank you

**Comment by theotherp** [comment]
The update to 2.13.1 encountered an issue where the old version could not be removed properly. I can't explain why that happened. Some of the other updates required a database recreation which just takes some time. I don't see any other problems with updates in the logs.

I do see some errors in the log where java could not be properly started: `[Error 5] Access is denied` but it's hard to say what causes that.

The two instances are normal.

I have yet to find an explanation why hydra is slow from the internet or remote computers in general. When it doesn't respond at all, are you sure the instance is actually running and reachable?

There's occasionally a timeout when trying to connect DogNZB which is why it's temporarily disabled. The other one got disabled because you reached your request limit, probably because you made too many requests in a given time or you reached your API limit - you'd have to ask them.

If you think "stats are off" I'd need more specific examples.

Right now apart from the slow connection over internet I don't see anything that's wrong with the program, per se.

**Comment by AtariBaby** [comment]
So let me say these are not complaints! I like it even with these issues. Just trying to help by reporting what I see.

To be clear, external web access doesn't work for me at all anymore.

The indexer stats were wildly off before, but seem like they might be accurate now.

And maybe the java issue was the problem before, so you can close this, unless you want to discuss the external server access some more.

**Comment by theotherp** [comment]
> So let me say these are not complaints! I like it even with these issues. Just trying to help by reporting what I see.

I understand.

> To be clear, external web access doesn't work for me at all anymore.
Have you thought about putting your services behind a reverse proxy like nginx? It's a lot more secure and you only have to configure one service. As long as Hydra listens on the right interface (which it does because you configured the host to be 0.0.0.0) it doesn't care from where you access it. If it works locally it should work from somewhere else (provided the port is properly forwarded). I'm afraid I can't help there, sorry.

**Comment by AtariBaby** [comment]
I understand. The port is opened and was working. Quick question, currently if I’m on the local machine, I use 127.0.0.1:5076 instead of 0.0.0.0:5076 Is that a problem?

**Comment by theotherp** [comment]
Just to be clear: You never use 0.0.0.0 anywhere in your browser. It just means that the process will be reachable on all your IP addresses. Locally you can always use 127.0.0.1:5076, remotely you have to use your actual IP. Inside a LAN that might be something like 192.168.1.100, from the internet it's whatever https://whatismyipaddress.com/tells you.

**Comment by AtariBaby** [comment]
^yeah got that thanks, that’s not it. Oh well thanks for talking it through

**Comment by AtariBaby** [comment]
Here's an example of incorrect indexer stats. Fortunately, the indexer is currently temporarily disabled, despite the stats being incorrect on nzbhydra2.

**Comment by theotherp** [comment]
What about that is not correct?

Thanks for the sponsoring, btw 👍

**Comment by theotherp** [comment]
Is Hydra the only process making queries?

**Comment by AtariBaby** [comment]
Sorry i was having login issues before i posted the next image. It should be but I can try and check

**Comment by theotherp** [comment]
Ok, I can see the difference. 

My values in Hydra and on the dashboard are (nearly) identical. I think this indexer resets at 00:00 UTC. Have you configured "0" as hit limit reset time?

**Comment by theotherp** [comment]
I just saw in the forum that you asked that and that it's a rolling reset. I also saw in your debug infos that you configured a reset time. Try removing that.

**Comment by theotherp** [comment]
I also removed the second picture to prevent your API access from being disabled.

**Comment by AtariBaby** [comment]
oh thank you very much! I had tried to edit all out but that's great thank you

**Comment by AtariBaby** [comment]
The hit reset time was already 0 and the limit is 1000.

**Comment by theotherp** [comment]
Yes, my point is, remove the 0 for the reset time.

**Comment by AtariBaby** [comment]
ohhhhh

**Comment by AtariBaby** [comment]
I’ll report back if it’s still problematic. It works, I just thought you might want to know about the discrepancy but now perhaps it was my config.

Question: my top indexer is slug. Why is it red in the list of indexers? The others are all dark gray.

**Comment by theotherp** [comment]
Hover over the red cross, it should say "Disabled by system", usually because the API key is invalid or something like that. Re-enable it in the config and test it.

**Comment by AtariBaby** [comment]
this is what i mean. i don't see a red cross and there isn't on the other page (btw those x's look more brown to me than anything, on the stats page. (picture coming in a moment)

**Comment by theotherp** [comment]
Open the config for you the indexer and recheck the caps.

**Comment by AtariBaby** [comment]
oh that seems to. have worked thank you

**Comment by AtariBaby** [comment]
I have a quick update. I solved the issue of nzbhydra remote access. I was baffled because:
It worked before.
I have proper ports open on my router
I checked Windows Defender Firewall with Advanced Security and there were rules created for the exe file etc.
So I concluded it must be hydra. Well...
I went to www.yougetsignal.com and tested port 5076 and sure enough, the test said the port was closed.
So then I concluded it must be Windows Firewall.
I created an inbound rule for port 5076 and now everything is hunky dory. It *is* slow, but I can access hydra’s pages via web again. My only guess is that maybe something changed in Windows Firewall, either by update or by some glitch, that caused the Hydra port (and only the hydra port) become inaccessible externally.
![59CBC40F-8745-463D-981B-BB90C36BD807](https://user-images.githubusercontent.com/97095/74863435-863f4980-5313-11ea-8a19-acba7686050e.jpeg)
