### ISSUE TITLE
Indexer priority when using API seems to have no effect

### ISSUE THREAD

**Issue by fragande** [theotherp/nzbhydra2#502]
As described in the title. When using the API with Sonarr and Radarr the indexer priority doesn't seem to do anything. Today, for example, a release grabbed was available on four of my five configured indexers at time of search, yet it was grabbed from the _lowest_ scored indexer.

When doing a manual search for the release in nzbhydra2 it is listed correctly (in order with the highest scored indexer first as a parent and the rest as children when expanding using the "+" sign). Due to privacy concerns I'm not comfortable posting the log, but looking through the debug log I see the following:

`INFO --- [0.0-5076-exec-2] o.n.d.IndexerUniquenessScoreSaver        : Title: "*release_name*". Downloaded from: Indexer5. Indexers with same result: Indexer1, Indexer2, Indexer5. Indexers without result: Indexer4`

Here Indexer1 is the one with the **highest** priority score and so on. So it looks to me that despite finding the same results on four indexers, nzbhydra2 grabs the nzb from the indexer with lowest priority in this case. It seems API calls prioritize by post age rather than indexer score, while manual searches lists by priority score. At least this is consistent in the limited amount of testing I've done so far.

Is this expected behaviour? As grabs from Indexer1 have the highest completion rate by far I would really like to have nzbhydra2 prioritize it and only as a _last resort_ grab from other indexers in order of score.  In my use case post age has very little relevance. Would this be possible to achieve? As for the label, I'm not sure if this is a bug or a feature request as I'm unsure what the expected behaviour is.

**Comment by theotherp** [comment]
To analyze this further I'd need a log with some more debug information. If you don't want to provide that I can only guess what's going on...

As you removed the release name I don't even know what type of result it is. Are you sure that the grouping in the GUI is due to them being duplicates and not just results with the same name? Have you enabled "Show duplicate triggers" in the display options?

Two results are duplicates only if they link to the actual same upload, not just when they have the same name. So in this case it doesn't matter from which indexer you get the NZB. The indexer priority only determines which of these duplicates is returned in the API results.

Ignoring the age of a result would not make sense in most cases as usually newer results have a better chance of completion. So no, that is not possible.

**Comment by theotherp** [comment]
I should've mentioned that the log output you quoted is a bit misleading because at that point I don't have the information about actual duplicates anymore and just check for any results with the same name (which is good enough for that purpose).

**Comment by fragande** [comment]
> Have you enabled "Show duplicate triggers" in the display options?

I had not, I have now. I'm not sure what is does though. Seems to have no effect on the grouping of results. The grabbed release in question which is available on all five indexers is still displayed as one expandable list. All children are posts to different groups.

If I understand correctly nzbhydra2 will only use indexer priority if it finds duplicates of the same post (same group) and post age always supersedes indexer priority score for the _same release name_?

In that case I guess it's expected behaviour and doesn't at all do what I assumed. I guess it's a feature request then rather than a bug report. In my case it would make much more sense if indexer priority superseded post age. It would hugely cut back on the failed downloads for non-0day releases.

I'm wondering if this is also what's interfering with my setup of preferred release groups in Sonarr and Radarr. As of now lower scored release group releases often gets grabbed despite being higher scored ones being available on my preferred indexer. I often grab these manually. I'm guessing this is because nzbhydra2 prioritizes by age.

**Comment by theotherp** [comment]
The thing is, Hydra will always list all separate releases. 

If I did what you proposed with 5 differents uploads you would only get one result for the API call and never see any of the others. If the download of that one result fails there's no other releases to fall back to.

I don't think this makes sense to implement, sorry.

**Comment by fragande** [comment]
Ok, I think I've made more wrong assumptions as I don't understand why that would be the case if indexer priority would simply supersede post age for grab order. Or is this a case of Sonarr's failed download handling prioritizing post age and the only way for nzbhydra2 to do what I would like is to omit the results from the other indexers (for the same release) if those posts are younger?

I feel like my use case is not unique, but I may be wrong. I have one indexer which is often faster to index new releases and also has a higher completion rate, especially for non-0day. For 0day this is fine, but it's very counterintuitive that for non-0day this indexer is only use as an absolute last resort due to the post ages being slightly higher.

**Comment by theotherp** [comment]
Hydra just returns an aggregated list of results from all indexers - where actual duplicates (as described above) are found all but one are removed from these results, with the result from the indexer with the highest priority kept. 

If two results with the same name but different ages are found then they're kept in the results as-is. Hydra has no way of influencing which results are grabbed by *arr, for that to work it would need to remove all results from any iother indexer instead of the one from your priorised indexer, which would mean that is effectively has less results to choose from. If you want to change the way other tools grab the results you'll have to request that feature from them.
