### ISSUE TITLE
Jackett API fetch schedule

### ISSUE THREAD

**Issue by deathbybandaid** [theotherp/nzbhydra2#527]
I love the new jackett fetching feature!

Is there a clean way to trigger this with cron, or something?

**Comment by theotherp** [comment]
I'll think about it. How often do you change your jackett config...?

**Comment by theotherp** [comment]
It's not so easy because when you do it via GUI you provide the URL and API key to Jackett. You can't easily do that automatically. I thought about getting them from the already configured indexers but I can't determine which of them are jackett indexers. I don't think it's worth the effort, sorry. You'll have to to it manually once in a while.

**Comment by deathbybandaid** [comment]
No problem, it was just a thought.

I follow the jackett releases.atom and add new indexers (free ones)
