### ISSUE TITLE
Warning NZBHydra wrapper  is outdated

### ISSUE THREAD

**Issue by pven** [theotherp/nzbhydra2#566]
Everytime when I start nzbhydra I get a warning telling me NZBHydra wrapper  is outdated. When I download the newest, replace it, and restart nzbhydra the warning is still there.

I am currently running v2.21.0 (2020-05-08)

**Comment by theotherp** [comment]
Post your debug infos zip

**Comment by pven** [comment]
Can I mail it to you? (I don't want my logs on the internet)

**Comment by theotherp** [comment]
Just check the log for the wrapper warning to see which file is outdated. Make extra sure that you actually updated *all* files.

**Comment by pven** [comment]
I only replaced nzbhydra2wrapper.py ... :-D ... Let me look. I'll get back to this.

**Comment by pven** [comment]
Found it:
```
2020-05-09 18:39:30.981  WARN --- [http-nio-0.0.0.0-1] o.n.p.OutdatedWrapperDetector            : [ID: 97669, Host: 12.34.56.78] Outdated file: nzbhydra2. Expected hash: 7e6c6e78. Actual hash: cc8d02b2
```

**Comment by theotherp** [comment]
REPLACE ALL THE FILES

Do what the message says. Extract the zip into your folder, OVERWRITING ALL THE FILES. DO NOT extract only some files.

**Comment by pven** [comment]
Hmm, replacing nzbhydra2 in the root for nzbhydra2 (Linux) does not solve it:
```
2020-05-09 19:09:30.272  WARN --- [              main] o.n.p.OutdatedWrapperDetector            : Outdated file: nzbhydra2. Expected hash: 7e6c6e78. Actual hash: cc8d02b2
```

What did I miss?

**Comment by theotherp** [comment]
Just delete the file if you're not using it.

**Comment by pven** [comment]
That solved it. Thanks!

And thanks for the comment in 2.21.1 :-)

**Comment by brianjmurrell** [comment]
I don't understand why, when nzbhydra has it's own upgrading process, why I have to download a zip and unpack it.  Can you please explain why the upgrading process is not working?

**Comment by theotherp** [comment]
Because at least under windows you can't overwrite running executables. With linux I wasn't sure and the python files were never really supposed to be used outside of docker containers or perhaps macOS.

The update is done by the wrapper itself which never restarts. Implementing an update mechanism where the process restarts itself is really hard so I gave up. The wrappers are changed about twice a year so it wasn't worth the effort for me.

I probably could get the python files to update themselves and likely the linux executable as well but that would, of course, require a new change in the wrapper... And you'd still need to manually restart the whole process. So I think doing these steps twice a year is bearable ;-)

**Comment by brianjmurrell** [comment]
So, does the built-in upgrade process fetch the 60MB zip file when it updates or does it fetch some smaller "delta"-kinda update?

**Comment by brianjmurrell** [comment]
And here we go.... exactly why I didn't trust and want to unzip...

```
May 12 06:27:30 host systemd[23889]: Failed at step EXEC spawning /home/brian/nzbhydra2/nzbhydra2: Permission denied
$ ls -l /home/brian/nzbhydra2/nzbhydra2
-rw-r--r--. 1 brian brian 8699744 May  3 09:26 /home/brian/nzbhydra2/nzbhydra2
```

Easy fix, no execute permissions.  But still, a hiccup in the "exception" update process.

**Comment by theotherp** [comment]
It fetches the ZIP.
