### ISSUE TITLE
question about "I've added a feature"

### ISSUE THREAD

**Issue by AtariBaby** [theotherp/nzbhydra2#568]
version 2.21.1 on windows 10

"I've added a feature that allows NZBHydra to fall back to similar results when an NZB download fails. It only works if you've set the 'NZB access type' in the downloading config to proxy results. That way NZBHydra can recognize the failed download and automatically try a different one. This should prevent Sonarr & co from disabling NZBHydra due to failed downloads."

Is this something we should manually do, or nothing to worry about unless you're having problems?

**Comment by theotherp** [comment]
That depends. If your downloads rarely fail there's no reason to enable that option - on the other hand it certainly doesn't hurt, I guess.

I added that options because some users reported NZBHydra being disabled by sonarr because the latter tried to download an NZB from an indexer with limited NZB grabs. With the new feature that would not happen as long as long as there are other alternatives to download.

**Comment by AtariBaby** [comment]
Thank you!

**Comment by AtariBaby** [comment]
Ah FYI your app very smartly recognized that one of my indexers wouldn’t like that, and advised me to revert to “redirect from indexer”. So best left alone, in my case, I guess.

**Comment by theotherp** [comment]
Yeah, they're quite... special about that :-/
