### ISSUE TITLE
Does not complete search.

### ISSUE THREAD

**Issue by biship** [theotherp/nzbhydra2#612]
Searching gets to "Indexers finished: 10/10". Constant spinning ball right above window. Never completes.
Logs: https://drive.google.com/file/d/15CoZ-nVYufLpsSo9GHnWYu2Itfxo1eB2/view?usp=sharing

Unrelated:
I am using a VPN with a split tunnel. NZBHydra2 is not on the VPN.
The logs shows: local: 10.5.142.164 | remote: 192.168.0.44
Remote is the computer doing the search.
10.5.142.164 is the VPN IP.
NZBHydra2 is binding to the wrong IP.
We either need a way to bind it to an adaptor, or IP, or preferably any IP within a CIDR block (192.168.0.0/24).
This may not be my issue of course.

**Comment by albino1** [comment]
You need to post logs for him to look at.

**Comment by biship** [comment]
> You need to post logs for him to look at.

I have.

**Comment by albino1** [comment]
> I have.

Apologies, for some reason I thought that was a screenshot.  I'm just so used to nobody ever posting logs, I'm pretty much on automatic :)

**Comment by theotherp** [comment]
Regarding the IP: Hydra doesn't bind to any IP unless you tell it to. It just tries to find the local IP to open the browser to that IP and/or to log it. It's not so simple to determine the correct IP.

Please disable all logging markers unless you actually need the log output. It produces way too much output for me to be able to properly read the log. Shut down hydra and delete all files in the log folder. Then restart and reproduce the problem. Create new debug infos and post them. Please attach them here instead of uploading them to your gdrive.

**Comment by theotherp** [comment]
Also check the browser console for errors.

**Comment by TBhimdi** [comment]
Can confirm this issue. It's been happening for several versions, only during internal searches (API is fine). This morning I finally narrowed it down so that I could replicate it with a single indexer. It only occurs if I give it multiple search terms, same exactly indexer with only two search terms, works fine, multiple, then nope.

Pressing F12 in Chrome and showing the debug screen didn't show any errors in the console. Copying/pasting the same search URL (taken from the log) into a Chrome incognito shows an immediate result, so the indexer is sending back a result.

XXXX ZZZZ = works
XXXX <year> <resolution> YYYY ZZZZ = shows the "Searching... Please Wait" screen with 1/1 indexers finished and spinning ball

[nzbhydra-debuginfos-2020-12-05-08-43.zip](https://github.com/theotherp/nzbhydra2/files/5647163/nzbhydra-debuginfos-2020-12-05-08-43.zip)

**Comment by TBhimdi** [comment]
Just updated to v3.6.0. The first search I did was "XXXX ZZZZ" on a single provider (named in the log file above). Worked perfectly. The second search, "XXXX year resolution YYYY ZZZZ" on the same provider, got the Searching screen with spinning ball.

**Comment by theotherp** [comment]
@TBhimdi Sorry for the late response. I can't find the search terms you mentioned in the log. Can you send me the name of the indexer and the search term that will cause the error?

**Comment by TBhimdi** [comment]
@theotherp

Thanks for checking on in on this. I updated some days ago, and looks like the "Fix 'Searching...' window was not closed when all found results were being filtered." bug has fixed my issue!
