### ISSUE TITLE
Multiple NZBHydra 2 Questions

### ISSUE THREAD

**Issue by Bearmancer** [theotherp/nzbhydra2#613]
I am not a developer and I was told that the best place to get my Hydra queries solved was this page.

1. I have a lot of free (i.e. limited searches) accounts on sites like Simply and Slug which means I want to minimize the amount of searches on those sites. I usually search for TV shows or movies. Is there a way to configure Hydra so that if I get a 1080p file from my paid/free (Binsearch/NZBindex) accounts, it doesn't search Slug or Simply?
2. What does priority in indexers do?
3. Simply and Miatrix have a daily ten API hit limit but Hydra only shows my API hits as opposed to daily usage/daily limit as with Slug. How do I fix this? https://imgur.com/a/SV6zN4I
4. I got 14 hits on a search for a popular comedian but only see 5 results: https://imgur.com/a/FlTedpg 
Why the discrepancy?
5. I have NZBHydra 2 on my external hard disk. Does that mean I don't need to backup the application because I can launch it from any PC?

**Comment by theotherp** [comment]
First let me say that I don't think free accounts that severely limit the amount of API accesses are worth it. It's a lot of hassle for the chance of getting some more results once in a while. Identify two or three indexers that are worth it and stick with them.

1) No, because that would require a multistep search where some indexers are searched first and then others. That would be hard to implement and hard to configure.

2) If multiple indexers return the same result (as in linking to the same upload) the result from the indexer with the highest priority will be returned.

3) You need to enter the limits for these indexers in the config.

4) Probably duplicates. Enable the display of duplicates (see the "Display options" button to the left)

5) There's a builtin backup option.
