### ISSUE TITLE
Use X-Forwarded-Port instead of X-Forwarded-Host for proxy port information

### ISSUE THREAD

**Issue by alron** [theotherp/nzbhydra2#70]
I noticed in the 1.1.0 update that you now require X-Forwarded-Host to contain the port number in the nginx proxy config. This is improper (in my understanding of the use of the header), and we should be using the dedicated X-Forwarded-Port header to specify the port number used on the proxy.

This is less of a problem and more of a fyi.

**Comment by theotherp** [comment]
Thanks, that's actually a bug and not intended that way.

**Comment by alron** [comment]
Awesome, I figured it was something as simple. Thank for the response. 👍

**Comment by theotherp** [comment]
Hm I thought I had implemented it and now I'm not sure. That went through a couple of iterations. Apparently I even changed the Wiki. Not enough sleep lately.

**Comment by alron** [comment]
Functionally, it doesn't matter to me. One config is as good as the other, as long as it works. I just noticed it because I had already set all the usual headers and was surprised to see a message saying that I need to set the port on the host header. :)

**Comment by theotherp** [comment]
It's really hard to get it right because if no information about the port is available how do you know if the config is correct or if the user forgot to configure the header to be sent? So I thought it should be better to be safe than sorry. Not both work and you don't get a warning when x-forwarded-host doesn't contain the port.

**Comment by theotherp** [comment]
Actually caddy and apache include the port in x-forwarded-host by default.
