### ISSUE TITLE
Configure how many "files" are retrieved on search

### ISSUE THREAD

**Issue by DarrenPIngram** [theotherp/nzbhydra2#729]
* What do you want to happen?
* If not clear, why do you want it?
* Do you think it's something only you need or something that might be popular?
* If not clear, explain the use case.
I would like the option for a configuration to set the number of "files" (articles, search results) that are retrieved when you do a search, with "all" being an option. I know you can load extra results but to be honest I find that hit and miss with no confirmation it has "done" or not. Having the default allowing you to retrieve more/all files would be good from the get-go.

**Comment by theotherp** [comment]
Every indexer returns a maximum of 100 results per page (search). NZBHydra can show you up to 500 of these results per GUI page.

Changing that in any way would mean that each indexer is at least queried twice, meaning initial search times would double (or triple or whatever). 

I have thought about implementing it any way but currently don't plan to, mostly because that piece of code is a clusterfuck and hard to modify... I'll keep your request in mind, though.

**Comment by DarrenPIngram** [comment]
Thanks. In the interim would it be possible to look at the "load more"
button and maybe have a status shown (it seems not to show it working, and
you just have to guess if it has done anything/updated the number count?

‌

**Comment by pilonull** [comment]
To add on to this, I've noticed a certain indexer will return 1000 results, but all the others only return 100 results without the option to load more? Why is this?

**Comment by theotherp** [comment]
This should be fixed / improved as hydra will now load up to 1000 results per indexer.

**Comment by DarrenPIngram** [comment]
Yes, thank you.
