### ISSUE TITLE
Indexer "Disabled Permanently" with no (obvious?) means to repair

### ISSUE THREAD

**Issue by ghost** [theotherp/nzbhydra2#74]
A search on an indexer generated the following error:

`ERROR --- [ol-210-thread-5] org.nzbhydra.indexers.Newznab            : [Search: 485745, IP: x.x.x.x] MyIndexer: Indexer refused authentication`

`WARN --- [ol-210-thread-5] org.nzbhydra.indexers.Newznab            : [Search: 485745, IP: x.x.x.x] MyIndexer will be permanently disabled until reenabled by the user`

On the indexer status page it shows:

`Indexer Last failure    Disabled until  Reason`

`MyIndexer date time         date time Permanently    Indexer refused authentication. Error code: 100`

There is no way that I know of to re-enable the indexer.  It looks perfectly normal on the Config/Indexers page.  I've changed the API key, re-checked capabilities, and in one case deleted and re-added the indexer.

NZBHydra v1.1.0

**Comment by theotherp** [comment]
You didn't follow the issue guidelines. You didn't post debug infos with
debug log level.

Am 18.01.2018 01:04 schrieb "Alrescha-git" <notifications@github.com>:

A search on an indexer generated the following error:

ERROR --- [ol-210-thread-5] org.nzbhydra.indexers.Newznab : [Search:
485745, IP: x.x.x.x] MyIndexer: Indexer refused authentication

WARN --- [ol-210-thread-5] org.nzbhydra.indexers.Newznab : [Search: 485745,
IP: x.x.x.x] MyIndexer will be permanently disabled until reenabled by the
user

On the indexer status page it shows:

Indexer Last failure Disabled until Reason

MyIndexer date time date time Permanently Indexer refused authentication.
Error code: 100

There is no way that I know of to re-enable the indexer. It looks perfectly
normal on the Config/Indexers page. I've changed the API key, re-checked
capabilities, and in one case deleted and re-added the indexer.

NZBHydra v1.1.0

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/theotherp/nzbhydra2/issues/74>, or mute the thread

**Comment by Alrescha-git** [comment]
> You didn't follow the issue guidelines. You didn't post debug infos with
debug log level.

True, but I'm not in control of the indexer.  I can't just turn on logging and make it fail for you.

**Comment by theotherp** [comment]
In the indexer statuses dialog there should be an icon looking like this: <img src="https://insidemartialartsmagazine.com.au/images/glyphicons/glyphicons-halflings/svg/individual_svg/glyphicons-halflings-13-ok.svg"  width="30px"/> Click it to reenable the indexer. If it's not there that's a bug and I apologize.

With the debug infos I at least knew what indexer it is, right? But why would you want to help me help you...

Error code 100 a newznab specified error code for wrong credentials.
