### ISSUE TITLE
1.1.2 broke Sickrage again

### ISSUE THREAD

**Issue by Hobbabobba** [theotherp/nzbhydra2#82]
i am so sorry, but the update from 1.1.1 to 1.1.2 broke hydra2 for the sickrage users again. the fetching of the nzb from the url is broken.

[nzbhydra-debuginfos-2018-01-21-20-32.zip](https://github.com/theotherp/nzbhydra2/files/1650123/nzbhydra-debuginfos-2018-01-21-20-32.zip)

**Comment by theotherp** [comment]
What exactly does not work? The log shows multiple results being downloaded completely.

**Comment by theotherp** [comment]
Just tested it with SickRage and was able to download an NZB.

**Comment by theotherp** [comment]
Also works when accessed via nginx reverse proxy.

**Comment by Hobbabobba** [comment]
nzbget can´t download the the nzb from hydra. it tries to fetch from the url, but doesn´t download the nzb-file

**Comment by theotherp** [comment]
Ooh, but that has nothing to do with SickRage, right?

**Comment by Hobbabobba** [comment]
gotcha. outch. yes, SR get´s everything right. Sends the data to nzbget and works fine. Just nbzget can´t fetch the file. sorry for the wrong title.

**Comment by theotherp** [comment]
Alright, got it.

I'll add an automated test that hopefully covers this scenario. Sorry about that, it was hard to catch and reproduce because it only happens when you download multiple NZBs from the same instance. All my tests verify that an NZB can be downloaded successfully and then shut down. You have to know that multiple downloads cause an error to write a test for that scenario.

**Comment by theotherp** [comment]
New version with fix coming in a couple of minutes.

**Comment by theotherp** [comment]
There it is
