### ISSUE TITLE
Handle Magnet links from torznab indexers

### ISSUE THREAD

**Issue by TChilderhose** [theotherp/nzbhydra2#83]
* What do you want to happen?

NZBHydra2 to handle torrent magnet links and download the associated .torrent file. Currently NZBHydra2 throws an exception if the link from a Torznab search is a magnet. If logs are needed I can provide some. There seems to be some projects that can do this 
https://github.com/danfolkes/Magnet2Torrent
https://github.com/killwing/magnet2torrent
https://github.com/xrgtn/mag2tor

**Comment by theotherp** [comment]
Yeah, I completely forgot about that scenario.

Am 21.01.2018 10:50 nachm. schrieb "TChilderhose" <notifications@github.com
>:

How to request a new feature

   - What do you want to happen?
   NZBHydra2 to handle torrent magnet links and download the associate
   .torrent file. Currently NZBHydra2 throws an exception if the link from a
   Torznab search is a magnet. If logs are needed I can provide some

There seems to be some projects that can do this https://github.com/xrgtn/
mag2tor

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/theotherp/nzbhydra2/issues/83>, or mute the thread

**Comment by TChilderhose** [comment]
Ah okay. From my experience there seems to be two types of magnets. One is just a url that starts with 

> magnet:?xt=urn:btih:

and the others are .magnet files with it's contents being that url.

**Comment by theotherp** [comment]
Can you recommend any free indexers that use those kinds of links?

**Comment by TChilderhose** [comment]
Not sure what you're using for it, but I'm using Jackett for torrents.

ETTV - .magnet file
The Pirate Bay - magnet url

**Comment by theotherp** [comment]
Sorry, I completely misunderstood you. As I said converting magnet links to torrent files requires external services or something like that and that's not something I want to introduce because then I have to test it and what not.

**Comment by theotherp** [comment]
I *might* be able to send the magnet link to the associated program. That would obviously not work on docker and I don't even know if that functionality exists on linux.

**Comment by TChilderhose** [comment]
Quite a large number of Debian Linux (what Ubuntu is based on) have default application functionality built-in. Opening magnet links in web browsers will open it in the default torrent client.

**Comment by theotherp** [comment]
I'll see what I can do.

**Comment by theotherp** [comment]
Looks good. Will have to do some more tests but it seems to work.

**Comment by theotherp** [comment]
Added in new version.
