### ISSUE TITLE
[Display issue] Age of search results not respecting pubDate correctly if local differential hours and minutes is present

### ISSUE THREAD

**Issue by NotAPirate1** [theotherp/nzbhydra2#869]
As requested an official issue for this topic.

I have found some weird behavior of `NZBHydra 2` regarding the displayed time (column `Age`) for a search result **if there is a local differential** in the `pubDate` tag present.

Example input XML for a search result:
```
<rss>
  <channel>
    <item>
      <pubDate>Mon, 22 May 2023 10:16:42 +0200</pubDate>
    </item>
  </channel>
</rss>
```

Should be `12:16:42` AFTER calculating the timezone, however NZBHydra 2 is displaying the time as `08:16:42`

In order to get this working, I have to switch plus and minus for the timezone offset, which will give me incorrect results for all other applications. Also when doing so the `W3C XML Validator` will throw some `Implausible date` errors (Date is in the future).

https://validator.w3.org/feed/docs/warning/ImplausibleDate.html

There is no issue with GMT formatted times.

More information:
NZBHydra 2 Version: 5.1.8

Specs: https://www.w3.org/Protocols/rfc822/#z28

Best regards

**Comment by theotherp** [comment]
Sorry for the late response, I was on vacation. That does look wrong.

**Comment by theotherp** [comment]
Uhm, I don't think so. 
"Mon, 22 May 2023 10:16:42 +0200" is equivalent to "2023-05-22T08:16:42Z" because the "+0200" indicates that the TZ is two hours ahead of UTC, so we need to subtract two hours which is why we get 08:16:42. NZBHydra will show all dates and times at UTC, no conversion to local date is done. Perhaps I should add a "Z" to make that clear? I think that's where the confusion stems from?

**Comment by NotAPirate1** [comment]
Hi, Thanks for the response.

`NZBHydra will show all dates and times at UTC, no conversion to local date is done` 

That's good to know and explains everything.
