### ISSUE TITLE
Category mapping fallback improvements

### ISSUE THREAD

**Issue by pannal** [theotherp/nzbhydra2#880]
Hey,

I'm currently using an indexer that uses German categories starting with TV DE 5100.

When adding their subcategories to nzbhydra this works, but when nzbhydra falls back to the parent category, it falls back to 5000 when the subcategories are of type TV.

This results in no search results. I think it should be possible to map categories to parent categories instead of hardcoded types.

**Comment by theotherp** [comment]
I'm not sure I understand the problem. 

5000 is a parent category of 5100. Searching for 5000 should return all TV results including the ones from 5100. 

If that indexer uses values > 5100 for anything but TV they're doing it wrong.

**Comment by pannal** [comment]
Yeah it doesn't yield any results when 5000 is used, though, as they use 5100 for german TV series and 5000 for non-german.

**Comment by theotherp** [comment]
I'm actually not sure what the specification says about that but it's the only indexer behaving like that. Any other indexer will map results that have category 5010 also with category 5000. 5000 is a catch-all for TV and they should follow that. I'm don't think I want to change my whole logic for one indexer and this isn't something that's easy to implement otherwise.

**Comment by pannal** [comment]
OK, thank you anyways :)
