### ISSUE TITLE
Bitdefender Security flagging exe in latest Windows version - NZBHydra2.exe is infected with Trojan.GenericKD.70500498

### ISSUE THREAD

**Issue by rdcrampton** [theotherp/nzbhydra2#901]
Attempting to update to the latest version after encountering some issues on my Windows 11 Pro machine.  As soon as I unpack the ZIP file, Bitdefender is flagging NZBHydra2.exe as a generic trojan and placing it in quarantine.  

"The file C:\Users\regcr\Downloads\nzbhydra2-5.3.3-windows\NZBHydra2.exe is infected with Trojan.GenericKD.70500498"

![Screenshot 2023-11-23 172641](https://github.com/theotherp/nzbhydra2/assets/17489362/fa882756-eef4-4820-af19-117ba053441e)

**Comment by theotherp** [comment]
It's a false positive, you'll have to add it to the exclusions.

**Comment by d4k0** [comment]
I have a similar problem with ESET since updating to 5.3.3, but in my case it concerns the file "NZBHydra2 Console.exe":

![2023-11-25_20-58-24](https://github.com/theotherp/nzbhydra2/assets/10982825/8cfda1fa-1f6f-4a0d-becb-7e08a9f5c3a5)

I have added the file to the exceptions and told ESET that it is a false positive.

Virustotal shows quite a few false positives for "NZBHydra2.exe" and "NZBHydra2 Console.exe":

https://www.virustotal.com/gui/file/dd78a06544d74a64adfc184cdd7d27dd0aa75c20b2567297c627ca1e16800d8d?nocache=1

https://www.virustotal.com/gui/file/b920a2305c5e90ee8cac329c40ba4c4dd903f7963c9994fa733eec9b5c39aa40?nocache=1

I also noticed that the automatic opening of the web UI at startup no longer works, although it is enabled in the settings.

**Comment by theotherp** [comment]
See https://github.com/pyinstaller/pyinstaller/issues/6754 (not the first one to link there).

I'll try if https://plainenglish.io/blog/pyinstaller-exe-false-positive-trojan-virus-resolved-b33842bd3184 works.

**Comment by theotherp** [comment]
Well, I got it down to 15: https://www.virustotal.com/gui/file/3558c9f64a640a19f902b988b272753bdf2c7c5f1eb9b64474da3eacacafcb0c?nocache=1 but BitDefender and Malwarebytes still report it :-(

**Comment by theotherp** [comment]
@pdukers Can't reproduce on Windows or with VirusTotal.

**Comment by theotherp** [comment]
Alright, found a solution which compiles exes that are by "only" 5/71 antivirus engines. The only one of those that I know is Malwarebytes. I'm gonna report it as a false positive.

**Comment by theotherp** [comment]
[nzbhydra2.exe](https://www.virustotal.com/gui/file/c648390b3aae1977280d46cf486972290e316a13f81fb0677537619810546818/detection) and [nzbhydra2 console.exe](https://www.virustotal.com/gui/file/dbe80ae901a21c6cbaa34219e46eed9325b9ab33d5075879d12852dc6fd83ce5?nocache=1). For some weird reason the console one is only flagged by three engines and one with systray is flagged by 9, but at least not by Bitdefender, Eset or Microsoft. If you use Avast, AVG or MalwareBytes you'll have to exclude i for now.

**Comment by theotherp** [comment]
Malwarebytes responded very quickly: https://forums.malwarebytes.com/topic/304986-nzbhydra2exe-and-nzbhydra2-consoleexe-both-compiled-with-pyinstaller/#comment-1601966

**Comment by theotherp** [comment]
This issue is obsolete / fixed with the new windows wrapper which doesn't use python anymore and produces no false positives.

**Comment by d4k0** [comment]
I can confirm that the problem has now been solved. ESET no longer displays a message. The automatic opening of the web UI at startup is now also working again. Thanks you!

**Comment by d4k0** [comment]
I can confirm that the problem has now been solved. ESET no longer displays a message. The automatic opening of the web UI at startup is now also working again. Thank you!
